data_loader:
  batch_size: 2
  data_path: events\m2p\pop1k7_m2p_{}\events
  train_split: events\m2p\pop1k7_m2p_functional\data_splits\train.pkl
  val_split: events\m2p\pop1k7_m2p_functional\data_splits\valid.pkl
  vocab_path: events\m2p\pop1k7_m2p_{}\dictionary.pkl
model:
  d_embed: 256
  d_ff: 1024
  d_model: 256
  feature_map:
    n_dims: 64
  max_len: 2048
  n_head: 4
  n_layer: 6 
  use_segemb: true
  n_segment_types: 2
training:
  gpuid: 0
  ckpt_dir: ckpt/perf/pop1k7_{}_new_gpt2
  ckpt_interval: 10       # epochs
  log_interval: 50       # steps
  lr: 1.0e-03
  lr_scheduler:
    T_max: 500000    # 160 epochs
    eta_min: 1.0e-05
  num_epochs: 1000
  trained_optim: null
  trained_params: null
  inference_params: null
  warmup_steps: 200
  accum_steps: 2
  patience: 50