data_loader:
  batch_size: 4
  data_path: events\c2m\emopia_c2m_{}\events
  train_split: events\c2m\emopia_c2m_functional\data_splits\train.pkl
  val_split: events\c2m\emopia_c2m_functional\data_splits\valid.pkl
  vocab_path: events\c2m\emopia_c2m_{}\dictionary.pkl
model:
  d_embed: 256
  d_ff: 512
  d_model: 256
  feature_map:
    n_dims: 64
  max_len: 768
  n_head: 4
  n_layer: 6 
  use_segemb: true
  n_segment_types: 2
training:
  gpuid: 0
  ckpt_dir: ckpt/melody/emopia_functional_new_gpt2
  ckpt_interval: 10
  log_interval: 50
  lr: 1.0e-05
  lr_scheduler:
    T_max: 500000
    eta_min: 1.0e-06
  num_epochs: 1000
  trained_optim: ckpt\melody\pop1k7_functional_new_gpt2\optim\best_optim.pt
  trained_params: ckpt\melody\pop1k7_functional_new_gpt2\params\best_params.pt
  patience: 50
  inference_params: null
  warmup_steps: 200
  accum_steps: 2