data_loader:
  batch_size: 4
  data_path: new_events/c2m/pop1k7_events_c2m_{}/events
  train_split: new_events/c2m/pop1k7_events_c2m_functional/data_splits/train.pkl
  val_split: new_events/c2m/pop1k7_events_c2m_functional/data_splits/valid.pkl
  vocab_path: new_events/c2m/pop1k7_events_c2m_{}/dictionary.pkl
model:
  d_embed: 256
  d_ff: 512
  d_model: 256
  feature_map:
    n_dims: 64
  max_len: 768
  n_head: 4
  n_layer: 6 
  use_segemb: true
  n_segment_types: 2
training:
  gpuid: 0
  ckpt_dir: ckpt/melody/pop1k7_full_song_{}_gpt2
  ckpt_interval: 10       # epochs
  log_interval: 50       # steps
  lr: 1.0e-03
  lr_scheduler:
    T_max: 500000    # 160 epochs
    eta_min: 1.0e-05
  num_epochs: 1000
  trained_optim: null
  trained_params: null
  inference_params: null
  warmup_steps: 200
  accum_steps: 2